# Generated by Django 4.1.3 on 2022-11-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
